In [1]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

for loopCount, iter in enumerate(xrange(1000)):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))                        

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print "Output After Training:"
print l1


[[-0.29929909]
 [-0.41433436]
 [ 0.67488946]
 [ 0.55621673]]


[[-0.32550793]
 [-0.45332188]
 [ 0.58004125]
 [ 0.44562275]]


[[-0.34051508]
 [-0.46955296]
 [ 0.50099676]
 [ 0.36933433]]


[[-0.34453622]
 [-0.46629908]
 [ 0.44395025]
 [ 0.32447521]]


[[-0.34157552]
 [-0.4518822 ]
 [ 0.40306197]
 [ 0.29818928]]


[[-0.33500245]
 [-0.43242729]
 [ 0.37221194]
 [ 0.28162202]]


[[-0.3268519 ]
 [-0.41146209]
 [ 0.34753851]
 [ 0.27004183]]


[[-0.31821753]
 [-0.39082366]
 [ 0.32686557]
 [ 0.26104964]]


[[-0.30964355]
 [-0.37136802]
 [ 0.30898669]
 [ 0.25345026]]


[[-0.30137786]
 [-0.35341708]
 [ 0.2932128 ]
 [ 0.24665668]]


[[-0.29351723]
 [-0.33702117]
 [ 0.27912381]
 [ 0.24038369]]


[[-0.2860853 ]
 [-0.32210437]
 [ 0.26644038]
 [ 0.23449273]]


[[-0.27907237]
 [-0.30854048]
 [ 0.2549597 ]
 [ 0.22891482]]


[[-0.27245505]
 [-0.29619054]
 [ 0.2445238 ]
 [ 0.2236132 ]]


[[-0.26620548]
 [-0.28492001]
 [ 0.23500363]
 [ 0.21856564]]


[[-0.26029558]
 [-0.27460589]
 [ 0.22629067]
 [ 0.21375

In [65]:
print "aal"

aal
